In [ ]:
import numpy as np

Q1 Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [ ]:
x = np.arange(4, dtype=np.int64)
a=np.shape(x)
X=np.ones(a,dtype=np.int64)
print(X)

[1 1 1 1]


Q2 Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [ ]:
X = np.array([[1, 2], [3, 4]])
b = np.matrix((X))

print(b)

[[1 2]
 [3 4]]


Q3 Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [ ]:

x = np.linspace(3., 10., 50)
print(x)


[ 3.          3.14285714  3.28571429  3.42857143  3.57142857  3.71428571
  3.85714286  4.          4.14285714  4.28571429  4.42857143  4.57142857
  4.71428571  4.85714286  5.          5.14285714  5.28571429  5.42857143
  5.57142857  5.71428571  5.85714286  6.          6.14285714  6.28571429
  6.42857143  6.57142857  6.71428571  6.85714286  7.          7.14285714
  7.28571429  7.42857143  7.57142857  7.71428571  7.85714286  8.
  8.14285714  8.28571429  8.42857143  8.57142857  8.71428571  8.85714286
  9.          9.14285714  9.28571429  9.42857143  9.57142857  9.71428571
  9.85714286 10.        ]


Q4 Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [ ]:
x=np.array( [[1, 2, 3], [4, 5, 6]])
x1=x.reshape(-1,order="F")
print(x1)

[1 4 2 5 3 6]


Q5 Let x be an array [1, 2, 3, ..., 9]. Split x into 3 arrays, each of which has 4, 2, and 3 elements in the original order.

In [ ]:
x=np.array([1,2,3,4,5,6,7,8,9])
x1=x[0:4]
x2=x[4:7]
x3=x[7:]
print(x1,x2,x3)

[1 2 3 4] [5 6 7] [8 9]


 Q6 Compute the inverse and primary diagnol sum of x=[[1,2],[3,4]]

In [ ]:
x=np.array([[1,2],[3,4]])
diag = np.diagonal(x)
print("the primary diagonal sum : ")
print(sum(diag))
inverse_x=np.linalg.inv(x)
print("inverse of matrix : ")
print(inverse_x)
print("diagonal sum of inverse: ")
print(sum(np.diagonal(inverse_x)))


the primary diagonal sum : 
5
inverse of matrix : 
[[-2.   1. ]
 [ 1.5 -0.5]]
diagonal sum of inverse: 
-2.4999999999999996


Q7 Sort x along the second axis. x = [[1,4],[3,1]]

In [ ]:
a = np.array([[1,4],[3,1]])
np.sort(a, axis=1) 

array([[1, 4],
       [1, 3]])

Q8 Get the indices that would sort x(as above) along the second axis.

In [ ]:
a = np.array([[1,4],[3,1]])
ind = np.argsort(a, axis=1)  
ind

array([[0, 1],
       [1, 0]])

Initiate x as a 2x5 array with random values from 0 to 10(not inclusive).Get the maximum and minimum values and their indices of x along the second axis.

In [ ]:
from numpy import random
x = random.randint(0,high=10, size=(2, 5))

max_x=np.amax(x, axis=1) 
min_x=np.amin(x, axis=1) 
max_indice_x=np.argmax(x,axis=1)
min_ind=np.argmin(x,axis=1)
print( x  , max_x , min_x ,  max_indice_x ,  min_ind)

[[6 4 0 8 3]
 [7 1 1 6 1]] [8 7] [0 1] [3 0] [2 1]


Run the following load command to get the 2-Dim iris dataset. Do the following operations on it.

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


Drop rows that contain a missing value. 

In [ ]:
iris_2d=iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0]
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

Find the correlation between first two columns.

In [ ]:
import scipy.stats
x=iris_2d[:,0]
y=iris_2d[:,1]
xy=np.array([x,y])
scipy.stats.linregress(xy)

LinregressResult(slope=-0.057268233797164836, intercept=3.3886373794881, rvalue=-0.10936924995064938, pvalue=0.18276521527136969, stderr=0.042783331776956604)

Find the mean,median and standard deviation of column 3.

In [ ]:
x=iris_2d[:,2]
print(np.mean(x))
print(np.median(x))
print(np.std(x))

3.758666666666666
4.35
1.7585291834055212


Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [ ]:
l=[[22*i[2]*i[0]*i[0]/21] for i in  iris_2d ]
print(l)
iris_new=np.append(iris_2d,l , axis = 1)
print(iris_new)

[[38.14799999999999], [35.214666666666666], [30.084476190476195], [33.25142857142856], [36.666666666666664], [51.93257142857143], [31.03466666666666], [39.285714285714285], [28.394666666666673], [37.730000000000004], [45.82285714285715], [38.61942857142857], [33.791999999999994], [21.307523809523808], [42.29028571428571], [51.05571428571429], [39.71314285714287], [38.14799999999999], [57.863142857142854], [40.872857142857136], [51.93257142857143], [40.872857142857136], [22.167619047619045], [46.32257142857142], [45.860571428571426], [41.904761904761905], [41.904761904761905], [42.49142857142857], [39.65866666666667], [37.02704761904762], [38.61942857142857], [45.82285714285715], [42.49142857142857], [44.36666666666666], [37.730000000000004], [31.428571428571427], [41.19761904761905], [37.730000000000004], [26.3664761904762], [40.872857142857136], [34.04761904761905], [27.578571428571433], [26.3664761904762], [41.904761904761905], [51.77228571428571], [33.791999999999994], [43.597714285

Run the following loaad command and solve the following questions

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')


Find the count of unique species.

In [ ]:

l=iris[:,4]
species,count=np.unique(l, return_counts=True)
print(count)

[50 50 50]


Bin the petal length (3rd) column of iris_2d to form a text array, such that if petal length is:
Less than 3 –> ‘small’
3-5 –> ‘medium’
‘>=5 –> ‘large’

In [ ]:

bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5])


labels = {1: 'small', 2: 'medium', 3: 'large'}
text_array_petal_length = [labels[x] for x in bin]
print(text_array_petal_length)


['small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'small', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'medium', 'large', 'large', 'large', 'large', 'large', 'large

Find the most frequent value of petal length (3rd column) in iris dataset

In [ ]:
l=list(map(float,iris[:,2]))
w= np.array(l)
uniqw, inverse = np.unique(w, return_inverse=True)
bin_count=np.bincount(inverse)
max_index_row = np.argmax(bin_count)

print(uniqw[max_index_row])

1.5
